name: mf_bluetooth_printer
description: A Flutter package for MF Bluetooth Printer â€” print receipts to Bluetooth thermal printers via ESC/POS.
version: 1.0.1
homepage: https://github.com/mufastp/bluetooth_thermal_printer
repository: https://github.com/mufastp/bluetooth_thermal_printer
issue_tracker: https://github.com/mufastp/bluetooth_thermal_printer/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.0
  image: ^4.0.0
  permission_handler: ^11.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
